var gfc_Qn=osapi,gfc_Rn="ceil";gfc_1[gfc_].share=gfc_ad(25,function(){gfc_hn();return!1});gfc_wa(gfc_M[gfc_],gfc_ad(21,function(){this.x=gfc_g[gfc_Rn](this.x);this.y=gfc_g[gfc_Rn](this.y);return this}));gfc_wa(gfc_2e[gfc_],gfc_ad(20,function(){gfc_ta(this,gfc_g[gfc_Rn](this[gfc_l]));gfc_Qa(this,gfc_g[gfc_Rn](this[gfc_H]));return this}));
gfc_wa(gfc_Mg[gfc_],gfc_ad(19,function(){this.top=gfc_g[gfc_Rn](this.top);gfc_Ta(this,gfc_g[gfc_Rn](this[gfc_8c]));gfc_Ja(this,gfc_g[gfc_Rn](this[gfc_pc]));gfc_Ba(this,gfc_g[gfc_Rn](this[gfc_w]));return this}));gfc_wa(gfc_Ng[gfc_],gfc_ad(18,function(){gfc_Ba(this,gfc_g[gfc_Rn](this[gfc_w]));this.top=gfc_g[gfc_Rn](this.top);gfc_ta(this,gfc_g[gfc_Rn](this[gfc_l]));gfc_Qa(this,gfc_g[gfc_Rn](this[gfc_H]));return this}));
gfc_1[gfc_].Fi=gfc_ad(17,function(){var a=this.xd;a.valid?(this.d=this.Cg(this.xd),this.Mh(a[gfc_Vb])):(this.xd=null,this.render(a.actions,a[gfc_Vb],a.params));this.Bg()});gfc_1[gfc_].Af=gfc_ad(14,function(){return this.Cb.pop()});gfc_1[gfc_].ni=gfc_ad(5,function(a,b,c){return a?c<b?[]:a[gfc_kb](gfc_g.min(b,a[gfc_j]),gfc_g.min(c,a[gfc_j])):[]});
var gfc_Sn=function(a){return a=gfc_d.friendconnect_serverBase+"/friendconnect/favicon?url="+escape(a)},gfc_7=function(a,b,c){this.Ea();this.$q();var d=new gfc_Q;d.set("members",{action:this.iu,callback:this.et});d.set("member-page",{action:this.hu,callback:this.dt});d.set("blocked-member-page",{action:this.bu,callback:this.Zs});d.set("profile-friends-page",{action:this.nu,callback:this.it});d.set("sitesData",{action:this.vu,callback:this.mt});d.set("viewerFriends",{action:this.Au,callback:this.ot});
d.set("profileData",{action:this.mu,callback:this.ht});d.set("blockUser",{action:this.au,callback:this.Ys});d.set("unblockUser",{action:this.yu,callback:this.nt});d.set("profileFriends",{action:this.ou,callback:this.jt});d.set("activityData",{action:this.Kf,callback:this.hd});d.set("sendFriendRequest",{action:this.uu,callback:this.lt});d.set("sendFriendRequestResponse",{action:this.eu,callback:this.Wl});d.set("deleteActivity",{action:this.Lf,callback:this.hd});d.set("requestAndProcessViewerNumWaitingMessages",
{action:this.Bu,callback:this.qt});d.set("requestPromo",{action:this.pu,callback:this.kt});this.gb=null;this.Tw=new gfc_pn("fc-members-options-menu",gfc_J(this.Cs,this),gfc_J(this.Bs,this),gfc_J(this.Ds,this),0,gfc_d.friendconnect_serverBase,this.f("ENDCAP_LINK_COLOR")||"0000cc",this.f("CONTENT_TEXT_COLOR")||"000000");this.Gv=!1;this.Aa=10;this.vf=15;this.gn=10;var e=gfc_gh(gfc_Wg()),f=gfc_Tn;this.Sb=3;this.oc=8;this.vm=null;this.oa=this.oc*this.Sb;this.slimTopCapHeight=19;this.tinyTopCapHeight=8;
this.isMessagingEnabled=a;this.isPromosEnabled=b;this.isSocialShareEnabled=c;this.numWaitingMessages=0;this.promoCode=-1;this.promoHtml=null;this.Mb=new gfc_ln;this.Gh()&&(a=(a=this.f(f.FACE_SIZE))?gfc_fa(a):32,a+=6,this.Sb=gfc_g[gfc_rb]((e[gfc_l]-10)/a),e=340,e=this.f(f.HEIGHT),b=this.f(f.NUMBER_ROWS),f=27,b?(this.oc=gfc_fa(b),e=this.oc*a,this.vm=e+f):e&&(e=gfc_fa(e)-96,this.oc=gfc_g.max(2,gfc_g[gfc_rb](e/a)),this.vm=this.oc*a+f),this.oa=this.oc*this.Sb);gfc_1[gfc_y](this,d)};gfc_7.inherits(gfc_1);
gfc_Ha(gfc_7[gfc_],function(){gfc_7.i[gfc_A][gfc_y](this);gfc_Um("start");var a=gfc_a[gfc_k][gfc_Zb](),b=gfc_ja();(a=b.profileId||a.profileId)?(b={},b[gfc_e[gfc_q][gfc_F].ID]=a,a=new gfc_e[gfc_q](b),this.render(["profileData","profileFriends","activityData"],"profile",{person:a})):(a=["members","viewerFriends"],this.isMessagingEnabled&&a[gfc_i]("requestAndProcessViewerNumWaitingMessages"),this.isPromosEnabled&&!this.Fb()&&a[gfc_i]("requestPromo"),this.render(a,"faces"))});gfc_7[gfc_].e={};
gfc_7[gfc_].Ea=function(){this.e.MSG_SITE_MEMBERS="Members";this.e.MSG_BE_THE_FIRST="Be the first!";this.e.MSG_NO_SITE_MEMBERS="There are no members yet.";this.e.MSG_ALL_SITE_MEMBERS="All Members";this.e.MSG_ALL_BLOCKED_MEMBERS="All Blocked Members";this.e.MSG_NO_BLOCKED_MEMBERS="You have not blocked any members";this.e.MSG_YOUR_FRIENDS="Your Friends";this.e.MSG_ALL_YOUR_FRIENDS="All Your Friends";this.e.MSG_JFJ="Join and connect with others!";this.e.MSG_MANAGE="Manage members";this.e.MSG_SETTINGS=
"Settings";this.e.MSG_OPTIONS="Options";this.e.MSG_INVITE="Invite";this.e.MSG_MEMBERS_SHARE="Share this page";this.e.MSG_BACK="Back";this.e.MSG_BACK_TO_TOP="Home";this.e.MSG_VIEW_MY_PROFILE="View my profile";this.e.MSG_ABOUT_ME="About me";this.e.MSG_MORE="More \u00bb";this.e.MSG_SHOW_BLOCKED="Show blocked members \u00bb";this.e.MSG_SHOW_ALL="\u00ab Show all members";this.e.MSG_INVITE_YOUR_FRIENDS="Invite your friends";this.e.MSG_LINK_IN_NETWORKS="Link in your social networks";this.e.MSG_ACTIVITIES=
"Activities";this.e.MSG_ALL_ACTIVITIES="More activities";this.e.MSG_DELETE_THIS="Delete";this.e.MSG_SITES="Sites I've joined";this.e.MSG_ALL_SITES="More sites I've joined";this.e.MSG_LINKS="Links";this.e.MSG_ALL_LINKS="More links";this.e.MSG_NO_ACTIVITIES="No activities to show";this.e.MSG_ADD_AS_FRIEND="Add as friend";this.e.MSG_SEND_MESSAGE="Send a message";this.e.MSG_BLOCK_USER="Block this user";this.e.MSG_UNBLOCK_USER="Unblock this user";this.e.MSG_USER_IS_ADMIN="Administrator";this.e.MSG_JOIN=
"Join this site";this.e.MSG_OR="or";this.e.MSG_SIGN_IN="Sign in";this.e.MSG_SIGN_OUT="Sign out";this.e.MSG_PREVIOUS="\u00ab Previous";this.e.MSG_NEXT="Next \u00bb";this.e.MSG_NEWER="\u00ab Newer";this.e.MSG_OLDER="Older \u00bb";this.e.MSG_ACCEPT_ALL_FRIEND_REQUESTS="Accept all";this.e.MSG_HELP_FRIENDREQUEST="You and your friends will see each other across all Friend Connect sites.";this.e.MSG_HELP_FRIENDINVITE="Once you are friends, you will see each other across all Friend Connect sites.";this.e.MSG_HELP_BLOCKMEMBER=
"Blocking a visitor removes them from the members list and prevents them from interacting with other visitors on your site";this.e.MSG_INVITATION="Invitation:";this.e.MSG_SEND="Send";this.e.MSG_BLOCK="Block";this.e.MSG_IGNORE="Ignore";this.e.MSG_CANCEL="Cancel";this.e.MSG_SITE_SETTINGS="Site settings";this.e.MSG_INVITE_FRIENDS="Invite friends";this.e.MSG_ABOUT_FC="About Friend Connect";this.e.MSG_ALREADY_MEMBER="Already a member?";this.e.MSG_EDIT_PROFILE="Edit profile"};gfc_7[gfc_].qa={};
gfc_7[gfc_].$q=function(){this.qa.MSG_SITE_MEMBERS="Followers";this.qa.MSG_NO_SITE_MEMBERS="There are no followers yet.";this.qa.MSG_SHOW_BLOCKED="Show blocked followers \u00bb";this.qa.MSG_SHOW_ALL="\u00ab Show all followers";this.qa.MSG_ALL_SITE_MEMBERS="All Followers";this.qa.MSG_ALL_BLOCKED_MEMBERS="All Blocked Followers";this.qa.MSG_NO_BLOCKED_MEMBERS="You have not blocked any followers";this.qa.MSG_LIKE_THIS_SITE="Like this blog?";this.qa.MSG_JOIN="Follow";this.qa.MSG_BACK_TO_TOP="Members";
this.qa.MSG_JFJ="Follow and connect with your friends!";this.qa.MSG_HELP_FRIENDREQUEST="You and your friends will see each other across all Following blogs and Friend Connect sites.";this.qa.MSG_HELP_FRIENDINVITE="Once you are friends, you will see each other across all Following blogs and Friend Connect sites."};
gfc_7[gfc_].L=function(a,b){var c=!0;if(b[gfc_B]&&b[gfc_B].person){var d={},e=b[gfc_B].person[gfc_Sb]()+" is your friend";d.MSG_IS_FRIEND=e;e="You have invited "+(b[gfc_B].person[gfc_Sb]()+" to be your friend");d.MSG_IS_INVITED=e;e=b[gfc_B].person[gfc_Sb]()+"'s friends";d.MSG_PROFILE_FRIENDS=e;e="All "+(b[gfc_B].person[gfc_Sb]()+"'s friends");d.MSG_ALL_PROFILE_FRIENDS=e;for(var f in d)this.g(a,f,d[f])}b.invitedBy&&b.invitedBy[gfc_Sb]()&&(d=gfc_f[gfc_l]?gfc_f[gfc_l]:gfc_f[gfc_u][gfc_gb]+2,c=(d-135)/
8,d=(d-175)/8,c="View "+(gfc_Im(b.invitedBy[gfc_Sb](),c)+"'s profile"),d=gfc_Im(b.invitedBy[gfc_Sb](),d)+" invited you to this site",this.g(a,"MSG_VIEW_INVITER_PROFILE",c),this.g(a,"MSG_INVITED_YOU",d),this.Gv=!0,c=!1);d=this.numWaitingMessages+" messages waiting for you.";this.isMessagingEnabled&&0<this.numWaitingMessages&&(c=!1,this.g(a,"showWaitingMessages",!0),this.isMessagingEnabled&&(this.g(a,"MSG_NUM_WAITING_MESSAGES",d),this.g(a,"MSG_VIEW_AND_CONFIGURE_MESSAGING","View messages")));b.friendRequests&&
(0<b.friendRequests[gfc_cb]()&&(c=!1),d=1==b.friendRequests[gfc_cb]()?"New friend request \u00bb":"New friend requests ("+(b.friendRequests[gfc_cb]()+") \u00bb"),this.g(a,"MSG_NEW_FRIEND_REQUESTS",d));if(this.gb){if(this.dl(this.gb.themeId))for(f in this.qa)this.g(a,f,this.qa[f]);this.gb.signInPrompt&&this.g(a,"MSG_JOIN",this.gb.signInPrompt);this.gb.signOutPrompt&&this.g(a,"MSG_SIGN_OUT",this.gb.signOutPrompt)}this.g(a,"isViewerAdmin",b.isViewerAdmin);this.g(a,"isMessagingEnabled",this.isMessagingEnabled);
this.g(a,"acceptMessages",this.Kn);this.g(a,"isViewingSelf",b.viewer&&b[gfc_B]&&b[gfc_B].person&&b.viewer[gfc_x]()==b[gfc_B].person[gfc_x]());d=!1;if(b.owner&&(e=b.owner[gfc_G]("profileExtensions")))for(f in e)d=!0;this.g(a,"communityHasProfile",d);this.g(a,"promoHtml",c?this.promoHtml:null);this.g(a,"insertHtml",function(a,b){gfc_ya(a,b)})};gfc_7[gfc_].dl=function(a){return"blogger"==a};gfc_7[gfc_].Sg=function(a,b,c,d){gfc_fn({id:a,text:b,version:this.dl(this.gb.themeId)?1:null,style:c},d)};
gfc_7[gfc_].P=function(a){function b(b,c){d.g(a,b,gfc_J(c,d))}this.g(a,"facesPerRow",this.Sb);for(var c in this.e)this.g(a,c,this.e[c]);var d=this;b("getThumbnail",this.wc);b("map",this.map);b("elide",gfc_Im);b("safeSlice",this.ni);b("showAllActivities",this.rv);b("transformActivity",this.dc);b("nextActivities",this.cs);b("previousActivities",this.Ls);b("showAllLinks",this.tv);b("transformLink",this.dw);b("nextLinks",this.gs);b("previousLinks",this.Ns);b("showAllSites",this.wv);b("transformSite",
this.ew);b("nextSites",this.ns);b("previousSites",this.Ts);b("showAllMembers",this.uv);b("showBlockedMembers",this.yv);b("showUnblockedMembers",this.Pv);b("nextMembers",this.hs);b("nextBlockedMembers",this.ds);b("previousMembers",this.Os);b("previousBlockedMembers",this.Ms);b("showAllProfileFriends",this.vv);b("nextProfileFriends",this.ms);b("previousProfileFriends",this.Ss);b("showAllViewerFriends",this.xv);b("nextViewerFriends",this.ps);b("previousViewerFriends",this.Us);b("isHome",this.Dh);b("goBack",
this.hh);b("goBackToHome",this.Iv);b("invite",this.invite);b("editSettings",this.Ab);b("signout",this.signout);b("signin",this.signin);b("viewProfile",this.An);b("blockUser",this.fj);b("unblockUser",this.hw);b("goToInviteFriend",this.iq);b("sendMessageDialog",this.Ru);b("goToBlockMember",this.hq);b("goToEditProfile",this.Ab);b("goToViewerProfile",this.jq);b("sendInvite",this.Qu);b("blockMember",this.bo);b("acceptFriendRequest",this.Jn);b("ignoreFriendRequest",this.Zq);b("viewFriendRequests",this.pw);
b("acceptAllFriendRequests",this.In);b("numPreviewFriends",this.Qp);b("numPreviewMembers",this.Rp);b("showInvitedBy",this.Yp)};
gfc_7[gfc_].wk=function(a){a=gfc_g.max(1,a?this.oc-1:this.oc);var b=this.d[gfc_n].members?this.d[gfc_n].members[gfc_cb]():0,c=this.d[gfc_n].friends?this.d[gfc_n].friends[gfc_cb]():0,b=gfc_g[gfc_Rn](b/this.Sb),c=gfc_g[gfc_Rn](c/this.Sb);b>gfc_g[gfc_Rn](a/2)?c>gfc_g[gfc_rb](a/2)?(b=gfc_g[gfc_Rn](a/2),c=gfc_g[gfc_rb](a/2)):b=gfc_g.max(0,a-c):c>gfc_g[gfc_rb](a/2)&&(c=gfc_g.max(0,a-b));b*=this.Sb;c*=this.Sb;return a={numMembers:b,numFriends:c}};gfc_7[gfc_].Rp=function(a){return this.wk(a).numMembers};
gfc_7[gfc_].Qp=function(a){return this.wk(a).numFriends};gfc_7[gfc_].hu=function(a,b){var c=gfc_e[gfc_E](),d={},e=gfc_e[gfc_v][gfc_yc];d[e.FILTER]="PUBLICLY_VISIBLE";d[e.FIRST]=b[gfc_A];d[e.MAX]=b.pageSize?b.pageSize:this.oa;var f=[gfc_e[gfc_q][gfc_F].ID,gfc_e[gfc_q][gfc_F][gfc_5a],gfc_e[gfc_q][gfc_F][gfc_Vc]];d[e[gfc_Bc]]=f;d[gfc_e[gfc_v].DataRequestFields.ESCAPE_TYPE]=gfc_e.EscapeType.NONE;c.add(c[gfc_9b](gfc_$d(),d),"ownerFriends");c[gfc_z](a)};
gfc_7[gfc_].dt=function(a){this.d[gfc_n].members=a.get("ownerFriends")[gfc_o]()};gfc_7[gfc_].bu=function(a,b){var c=gfc_e[gfc_E](),d={},e=gfc_e[gfc_v][gfc_yc];d[e.FIRST]=b[gfc_A];d[e.MAX]=b.pageSize?b.pageSize:this.oa;d[gfc_e[gfc_v].DataRequestFields.ESCAPE_TYPE]=gfc_e.EscapeType.NONE;e={};e[gfc_e[gfc_Za][gfc_F][gfc_Rb]]=gfc_e[gfc_Za].PersonId.OWNER;e[gfc_e[gfc_Za][gfc_F][gfc_tb]]="BLOCKED";e[gfc_e[gfc_Za][gfc_F][gfc_3a]]=1;e=gfc_e[gfc_3c](e);c.add(c[gfc_9b](e,d),"blockedMembers");c[gfc_z](a)};
gfc_7[gfc_].Zs=function(a){this.d[gfc_n].blockedMembers=a.get("blockedMembers")[gfc_o]()};gfc_7[gfc_].nu=function(a,b){var c=gfc_e[gfc_E](),d=b&&b.person&&b.person[gfc_x]()||this.v[gfc_B].person[gfc_x](),e={},f=gfc_e[gfc_v][gfc_yc];e[f.FIRST]=b[gfc_A];e[f.MAX]=b.pageSize?b.pageSize:this.oa;d=this.El(d);e[gfc_e[gfc_v].DataRequestFields.ESCAPE_TYPE]=gfc_e.EscapeType.NONE;c.add(c[gfc_9b](d,e),"profileFriends");c[gfc_z](a)};
gfc_7[gfc_].El=function(a){var b={};b[gfc_e[gfc_Za][gfc_F][gfc_Rb]]=a;b[gfc_e[gfc_Za][gfc_F][gfc_tb]]="FRIENDS";b[gfc_e[gfc_Za][gfc_F][gfc_3a]]=1;return gfc_e[gfc_3c](b)};gfc_7[gfc_].it=function(a){this.d[gfc_n][gfc_B].friends=a.get("profileFriends")[gfc_o]()};gfc_7[gfc_].Yi=function(a){for(var b=gfc_e[gfc_n].getDataContext(),c=0;c<a[gfc_j];c++){var d=a[c],d=b.getDataSet(d);if(!d||d.code)return!1}return!0};
gfc_7[gfc_].iu=function(a){var b=this.oa,c=!b||24==b;c&&gfc_e[gfc_n]&&this.Yi(["ownerFriends","viewer","siteSettings","friendRequests"])?a(gfc_e[gfc_n].getDataContext()[gfc_o]()):(c=gfc_Qn.newBatch(),b={userId:"@owner",groupId:"@friends",count:b,filterBy:"PUBLICLY_VISIBLE"},c.add("ownerFriends",gfc_Qn.people.get(b)),c.add("viewer",gfc_Qn.people.getViewer()),c.add("siteSettings",gfc_Qn.extensions.get({command:"GetSiteSettings"})),c.add("friendRequests",gfc_Qn.extensions.get({command:"GetFriendRequests",
params:'{"idSpec" : "VIEWER"}'})),(b=gfc_ja().psinvite)&&c.add("invitedBy",gfc_Qn.extensions.get({command:"DecodeInvitation",params:{token:b}})),c.execute(a))};gfc_7[gfc_].et=function(a,b){this.d[gfc_n].members=gfc_2d(a.ownerFriends,gfc_Yd);this.d[gfc_n].viewer=gfc_Yd(a.viewer);this.Wl(a,b,!0);this.gb=a[gfc_Cc];var c=gfc_ja();!c.psinvite||null!=this.d[gfc_n].viewer&&""!=this.d[gfc_n].viewer||(a.invitedBy&&(a.invitedBy.nickname=a.invitedBy.displayName),this.d[gfc_n].invitedBy=new gfc_e[gfc_q](a.invitedBy))};
gfc_7[gfc_].Au=function(a,b){b=b||{};var c=b.pageSize||this.maxFacesPerPage,d=!b[gfc_A]||0==b[gfc_A],e=!c||20==c;d&&(e&&gfc_e[gfc_n])&&this.Yi(["friends","isViewerAdmin"])?a(gfc_e[gfc_n].getDataContext()[gfc_o]()):(d=gfc_Qn.newBatch(),c={userId:"@viewer",groupId:"@friends",count:c},b[gfc_A]&&(c.startIndex=b[gfc_A]),d.add("friends",gfc_Qn.people.get(c)),d.add("isViewerAdmin",gfc_Qn.people.get({userId:"@viewer",groupId:"ADMINS"})),d.execute(a))};
gfc_7[gfc_].ot=function(a){var b=a.friends;b&&!b.error&&(this.d[gfc_n].friends=gfc_2d(b,gfc_Yd));this.Am(a)};gfc_7[gfc_].Bu=function(a){var b=gfc_e[gfc_E]();b.add(gfc_0d("VIEWER"),"numWaitingMessages");b[gfc_z](a)};gfc_7[gfc_].qt=function(a){this.numWaitingMessages=a.get("numWaitingMessages")[gfc_o]().numberOfWaitingMessages};
gfc_7[gfc_].pu=function(a){this.log("requesting promo");var b=new gfc_a[gfc_Lb],b=b.getLang()+(b[gfc_tc]()?"_"+b[gfc_tc]():""),c=gfc_e[gfc_E]();c.add(gfc_Qd("GetPromo",{hl:b}),"promo");c[gfc_z](a)};gfc_7[gfc_].kt=function(a){this.log("processing promo");(a=a.get("promo")[gfc_o]())&&-1!=a.promoCode&&(this.promoCode=a.promoCode,this.promoHtml=a.promoHtml)};
gfc_7[gfc_].Rn=function(){for(var a=function(){this.promoHtml=null;for(var a=gfc_Gf("div","fc-promo-main",gfc_O("peg")),b=0;b<a[gfc_j];b++)gfc_jh(a[b],!1);this.X();this.log("Dismissing promo "+this.promoCode);a=gfc_e[gfc_E]();a.add(gfc_Qd("DismissPromo",{promoCode:this.promoCode}));a[gfc_z](gfc_J(function(){this.log("The promo has been dismissed");this.promoCode=-1},this))},b=gfc_Gf("a","fc-promo-dismiss-link",gfc_O("peg")),c=0;c<b[gfc_j];c++){var d=b[c],e="click";gfc_$h(d,e);gfc_1h(d,e,gfc_J(a,this))}};
gfc_7[gfc_].Am=function(a){var b=a.isViewerAdmin;b&&!b.error?this.d[gfc_n].isViewerAdmin=b.list[gfc_j]:a.get&&a.get("isViewerAdmin")&&(a=a.get("isViewerAdmin"))&&!a[gfc_Hb]()&&(this.d[gfc_n].isViewerAdmin=a[gfc_o]()[gfc_cb]())};gfc_7[gfc_].In=function(a){var b=[];a.each(function(a){a={user:a[gfc_G](goog.opensocial.peoplesense.Invite[gfc_F].INVITER)[gfc_x](),action:"ACCEPT"};b[gfc_i](a)});this.render(["sendFriendRequestResponse","members","viewerFriends"],gfc_J(this.zg,this),{friendRequestResponses:b})};
gfc_7[gfc_].Iv=function(){this.ea();this.render(["members","viewerFriends"],"faces")};gfc_7[gfc_].Jn=function(a){a={user:a[gfc_x](),action:"ACCEPT"};this.render(["sendFriendRequestResponse","members","viewerFriends"],gfc_J(this.zg,this),{friendRequestResponses:[a]})};gfc_7[gfc_].pw=function(){this.ea();this.C("friend-requests")};gfc_7[gfc_].An=function(a){this.Fb()?(this.ea(),this.rw(a)):gfc_Nd(a[gfc_x]())};
gfc_7[gfc_].rw=function(a){this.render(["profileData","profileFriends","activityData"],"profile",{person:a})};gfc_7[gfc_].vu=function(a,b){var c=gfc_e[gfc_E](),d=gfc_e[gfc_v][gfc_yc],e={};e[d.FIRST]=b&&b[gfc_A]?b[gfc_A]:0;var f=this.d[gfc_n][gfc_B].person[gfc_x]();e[d.MAX]=this.gn;c.add(gfc_7d(gfc_e[gfc_3c]({userId:f}),e),"profileSites");c[gfc_z](a)};gfc_7[gfc_].mt=function(a){this.d[gfc_n][gfc_B].sites=a.get("profileSites")[gfc_o]()};
gfc_7[gfc_].mu=function(a,b){this.d[gfc_n].profile={};b=b||{};var c=b.person,d={},c=c[gfc_x](),e=gfc_e[gfc_E](),f=[gfc_e[gfc_q][gfc_F].ID,gfc_e[gfc_q][gfc_F][gfc_5a],gfc_e[gfc_q][gfc_F][gfc_Vc],gfc_e[gfc_q][gfc_F].ABOUT_ME,gfc_e[gfc_q][gfc_F].URLS,"profileExtensions"],g=gfc_e[gfc_v][gfc_yc];d[g[gfc_Bc]]=f;d[gfc_e[gfc_v].DataRequestFields.ESCAPE_TYPE]=gfc_e.EscapeType.NONE;e.add(e.newFetchPersonRequest(c,d),"profile");e.add(e.newFetchPersonRequest("VIEWER",d),"viewer");e.add(gfc_5d("VIEWER","ADMINS"),
"isViewerAdmin");e.add(e.newFetchPersonRequest("OWNER",d),"owner");this.gb||e.add(gfc__d(),"siteSettings");e.add(gfc_5d(c,"ADMINS"),"isAdmin");e.add(gfc_5d(c,"BLOCKED"),"isBlocked");this.isMessagingEnabled&&e.add(gfc_0d(c),"canMessage");e[gfc_z](a)};
gfc_7[gfc_].Kf=function(a,b){var c=b.person[gfc_x](),d=gfc_e[gfc_3c]({userId:c}),e=gfc_e[gfc_E]();(this.d[gfc_n].viewer&&c!=this.d[gfc_n].viewer[gfc_x]()||this.Fb())&&e.add(gfc_4d(b.person[gfc_x](),"VIEWER"),"isProfileFriend");e.add(e[gfc_Db](d,{}),"activities");e[gfc_z](a)};
gfc_7[gfc_].hd=function(a,b){null!=a.get("activities")[gfc_o]()&&(this.d[gfc_n][gfc_B].activities=a.get("activities")[gfc_o]());var c=a.get("isProfileFriend");c&&(b&&null!=this.d[gfc_n].viewer&&this.d[gfc_n].viewer[gfc_x]()!=b.person[gfc_x]())&&(this.d[gfc_n][gfc_B].isFriend=c[gfc_o]()[gfc_p])};
gfc_7[gfc_].ht=function(a,b){var c=a.get("profile")[gfc_o]();this.d[gfc_n][gfc_B].person=c;this.d[gfc_n][gfc_B].person.externalProfileUrl=null;var d=c[gfc_G](gfc_e[gfc_q][gfc_F].URLS),e=[];if(d)for(var f=0;f<d[gfc_j];f++){var g=d[f];"profile"!=g[gfc_G](gfc_e.Url[gfc_F].TYPE)&&"externalProfile"!=g[gfc_G](gfc_e.Url[gfc_F].TYPE)&&e[gfc_i](g);"externalProfile"==g[gfc_G](gfc_e.Url[gfc_F].TYPE)&&(this.d[gfc_n][gfc_B].person.externalProfileUrl=g[gfc_G](gfc_e.Url[gfc_F].ADDRESS))}this.d[gfc_n][gfc_B].links=
new gfc_Un(e,this.vf,0);this.d[gfc_n].owner=a.get("owner")[gfc_o]();this.d[gfc_n].viewer=a.get("viewer")[gfc_o]();(d=this.d[gfc_n].viewer)&&b.person[gfc_x]()!=this.d[gfc_n].viewer[gfc_x]()&&(this.d[gfc_n][gfc_B].isAdmin=a.get("isAdmin")[gfc_o](),this.d[gfc_n][gfc_B].isAdmin&&(this.d[gfc_n][gfc_B].isAdmin=this.d[gfc_n][gfc_B].isAdmin[gfc_cb]()),this.d[gfc_n][gfc_B].isBlocked=a.get("isBlocked")[gfc_o](),this.d[gfc_n][gfc_B].isBlocked&&(this.d[gfc_n][gfc_B].isBlocked=this.d[gfc_n][gfc_B].isBlocked[gfc_cb]()));
c=c[gfc_G]("profileExtensions");c=this.Mb.lf(c,this.Mb.vi);d=[];for(f in c){e=c[f];g={};g.title=e.title;var h=!1;if("SHORT_TEXT"==e.entryType||"LONG_TEXT"==e.entryType)e[gfc_p]&&e[gfc_p][gfc_fb]&&(g.body=[],g[gfc_u][gfc_i](e[gfc_p][gfc_fb]),h=!0);else if(e[gfc_p]&&e[gfc_p].choice&&0<e[gfc_p].choice[gfc_j]){g.body=[];for(h=0;h<e[gfc_p].choice[gfc_j];++h)g[gfc_u][gfc_i](e[gfc_p].choice[h][gfc_Rc]);h=!0}h&&d[gfc_i](g)}this.d[gfc_n][gfc_B].profileExtensions=d;this.gb||(this.gb=a.get("siteSettings")[gfc_o]());
this.isMessagingEnabled&&(f=(f=a.get("canMessage"))&&f[gfc_o]().canSendMessage,this.d[gfc_n][gfc_B].canSendMessage=f);this.Am(a)};gfc_7[gfc_].fj=function(a){this.render(["blockUser"],"profile",{person:a})};gfc_7[gfc_].hw=function(a){this.render(["unblockUser"],"profile",{person:a})};gfc_7[gfc_].map=function(a,b){var c=[],d=gfc_J(function(a,b,c){a[gfc_i](b(c))},this,c,b);a.each(d);return c};gfc_7[gfc_].uv=function(){this.ea();this.C("members-page")};
gfc_7[gfc_].yv=function(){this.ea();this.render(["blocked-member-page"],"blocked-members-page",{start:0})};gfc_7[gfc_].Pv=function(){this.Fi()};gfc_7[gfc_].hs=function(a){this.render(["member-page"],"members-page",{start:this.oa+a.getOffset()})};gfc_7[gfc_].Os=function(a){this.render(["member-page"],"members-page",{start:a.getOffset()-this.oa})};gfc_7[gfc_].ds=function(a){this.render(["blocked-member-page"],"blocked-members-page",{start:this.oa+a.getOffset()})};
gfc_7[gfc_].Ms=function(a){this.render(["blocked-member-page"],"blocked-members-page",{start:a.getOffset()-this.oa})};gfc_7[gfc_].xv=function(){this.ea();this.C("viewer-friends-page")};gfc_7[gfc_].ps=function(a){this.render(["viewerFriends"],"viewer-friends-page",{start:this.oa+a.getOffset()})};gfc_7[gfc_].Us=function(a){this.render(["viewerFriends"],"viewer-friends-page",{start:a.getOffset()-this.oa})};gfc_7[gfc_].vv=function(){this.ea();this.C("profile-friends-page")};
gfc_7[gfc_].ms=function(a){this.render(["profile-friends-page"],"profile-friends-page",{start:this.oa+a.getOffset(),person:this.d[gfc_n][gfc_B].person})};gfc_7[gfc_].Ss=function(a){this.render(["profile-friends-page"],"profile-friends-page",{start:a.getOffset()-this.oa,person:this.d[gfc_n][gfc_B].person})};gfc_7[gfc_].tv=function(){this.ea();this.C("links")};gfc_7[gfc_].gs=function(a){var b=this.vf+a.getOffset();this.d[gfc_n][gfc_B].links=new gfc_Un(a.all(),this.vf,b);this.C("links")};
gfc_7[gfc_].Ns=function(a){var b=a.getOffset()-this.vf;this.d[gfc_n][gfc_B].links=new gfc_Un(a.all(),this.vf,b);this.C("links")};gfc_7[gfc_].wv=function(){this.ea();this.C("sites")};gfc_7[gfc_].ns=function(a){this.render(["sitesData"],"sites",{start:this.gn+a.getOffset()})};gfc_7[gfc_].Ts=function(a){this.render(["sitesData"],"sites",{start:a.getOffset()-this.gn})};gfc_7[gfc_].rv=function(){this.ea();this.C("activities")};
gfc_7[gfc_].cs=function(a){this.render(["activityData"],"activities",{start:this.Aa+a.getOffset()})};gfc_7[gfc_].Ls=function(a){this.render(["activityData"],"activities",{start:a.getOffset()-this.Aa})};gfc_7[gfc_].af=function(a){this.render(["deleteActivity"],this.d[gfc_Vb],{activity:a})};gfc_7[gfc_].au=function(a,b){var c=gfc_e[gfc_E]();c.add(gfc_6d(b.person[gfc_x](),["BLOCKED"],[]),"block");this.bd();c[gfc_z](a)};
gfc_7[gfc_].Ys=function(a){if(a=!a.get("block")[gfc_Hb]())this.d[gfc_n][gfc_B].isBlocked=!0};gfc_7[gfc_].yu=function(a,b){var c=gfc_e[gfc_E]();c.add(gfc_6d(b.person[gfc_x](),[],["BLOCKED"]),"unblock");this.bd();c[gfc_z](a)};gfc_7[gfc_].nt=function(a){if(a=!a.get("unblock")[gfc_Hb]())this.d[gfc_n][gfc_B].isBlocked=!1};
gfc_7[gfc_].Lf=function(a,b){var c=b.activity,d=c[gfc_G](gfc_e[gfc_bc][gfc_F].ID),c=gfc_e[gfc_3c]({userId:c[gfc_G](gfc_e[gfc_bc][gfc_F][gfc_Rb])}),e=gfc_e[gfc_E]();e.add(gfc_Rd(d),"delete");e.add(e[gfc_Db](c,{}),"activities");e[gfc_z](a)};
gfc_7[gfc_].dc=function(a){var b=gfc_on,c=function(a){return a=a[gfc_m](/<a/g,"<a target='_top'")},d=null,e=this.d[gfc_n].viewer;null!=e&&a[gfc_G](gfc_e[gfc_bc][gfc_F][gfc_Rb])==this.d[gfc_n].viewer[gfc_x]()&&(d=gfc_J(this.af,this,a));(e=a[gfc_G](gfc_e[gfc_bc][gfc_F].STREAM_FAVICON_URL,{escapeType:"none"}))||(e=gfc_d.friendconnect_imageUrl+"/favicons.gif");return{icon:e,time:b(gfc_fa(a[gfc_G](gfc_e[gfc_bc][gfc_F].POSTED_TIME))),link:a[gfc_G](gfc_e[gfc_bc][gfc_F].STREAM_URL,{escapeType:"none"}),siteTitle:a[gfc_G](gfc_e[gfc_bc][gfc_F].STREAM_TITLE,
{escapeType:"none"}),innerHTML:c(a[gfc_G](gfc_e[gfc_bc][gfc_F].TITLE,{escapeType:"none"})),body:c(a[gfc_G](gfc_e[gfc_bc][gfc_F].BODY,{escapeType:"none"})),deleteHandler:d}};gfc_7[gfc_].ew=function(a){var b=gfc_a[gfc_xc].unescapeString,c=gfc_Sn;return{icon:c(a[gfc_G](gfc_e[gfc_q][gfc_F][gfc_jc])),link:a[gfc_G](gfc_e[gfc_q][gfc_F][gfc_jc]),title:b(a[gfc_Sb]())}};
gfc_7[gfc_].dw=function(a){var b=gfc_a[gfc_xc].unescapeString,c=gfc_Sn,d=a[gfc_G](gfc_e.Url[gfc_F].ADDRESS);return{icon:c(d),link:d,title:b(a[gfc_G](gfc_e.Url[gfc_F].LINK_TEXT))||d}};gfc_7[gfc_].ou=function(a,b){var c=gfc_e[gfc_E](),d=b.person[gfc_x](),e=gfc_e[gfc_v][gfc_yc],f=this.El(d),g={};g[gfc_e[gfc_v].DataRequestFields.ESCAPE_TYPE]=gfc_e.EscapeType.NONE;c.add(c[gfc_9b](f,g),"friends");f={};f[e.FIRST]=this.wx;f[e.MAX]=this.vx;c.add(gfc_7d(gfc_e[gfc_3c]({userId:d}),f),"profileSites");c[gfc_z](a)};
gfc_7[gfc_].Zq=function(a){a={user:a[gfc_x](),action:"DENY"};this.render(["sendFriendRequestResponse","members","viewerFriends"],gfc_J(this.zg,this),{friendRequestResponses:[a]})};gfc_7[gfc_].zg=function(a){return a&&a["next-view"]?a["next-view"]:["friend-requests"]};gfc_7[gfc_].uu=function(a,b){var c=b[gfc_B],d=gfc_e[gfc_E]();d.add(gfc_Sd(c[gfc_x](),b.message),"friendRequest");this.bd();d[gfc_z](a)};gfc_7[gfc_].lt=function(a){a.get("friendRequest")[gfc_Hb]()||(this.d[gfc_n][gfc_B].isInvited=!0)};
gfc_7[gfc_].eu=function(a,b){var c=gfc_Qn.newBatch(),d=b.friendRequestResponses;c.add("updateFriendRequest",gfc_Qn.extensions.get({command:"ProcessFriendRequests",params:'{"requests":'+gfc_a[gfc_gc].stringify(d)+"}"}));c.add("friendRequests",gfc_Qn.extensions.get({command:"GetFriendRequests",params:'{"idSpec" : "VIEWER"}'}));this.bd();c.execute(a)};gfc_7[gfc_].iq=function(){this.ea();this.C("invite-friend")};gfc_7[gfc_].Ru=function(a){this.isMessagingEnabled&&(a=a[gfc_G](gfc_e[gfc_q][gfc_F].ID),this.Su(a))};
gfc_7[gfc_].Su=function(a){if(this.isMessagingEnabled){a="/friendconnect/messaging/compose?recipientId="+a;var b=570,c=395;gfc_8m(a,gfc_c(b),gfc_c(c))}};gfc_1[gfc_].Kn=function(){var a="/friendconnect/messaging/accept",b=570,c=375;gfc_8m(a,gfc_c(b),gfc_c(c));return!1};gfc_7[gfc_].hq=function(){this.ea();this.C("block-member")};gfc_7[gfc_].jq=function(){this.An(this.d[gfc_n].viewer)};
gfc_7[gfc_].Qu=function(a){this.Af();a={profile:a};var b=gfc_O("inviteMessage");b&&(a.message=gfc_Fg(b));this.render(["sendFriendRequest"],"profile",a)};gfc_7[gfc_].bo=function(a){this.Af();this.fj(a)};gfc_7[gfc_].Wl=function(a,b,c){c=c||!1;this.d[gfc_n].friendRequests=gfc_2d(a.friendRequests,gfc_Ud);0<this.d[gfc_n].friendRequests[gfc_cb]()?b["next-view"]="friend-requests":b["next-view"]="faces";c||gfc_Um("friend")};
gfc_7[gfc_].jt=function(a){this.d[gfc_n][gfc_B].sites=a.get("profileSites")[gfc_o]();this.d[gfc_n][gfc_B].friends=a.get("friends")[gfc_o]()};gfc_7[gfc_].Yp=function(){return this.Gv};gfc_7[gfc_].X=function(){this.Tw.rebuild();this.Rn();gfc_a[gfc_0a].adjustHeight()};gfc_7[gfc_].Cs=function(a){return a=gfc_P("span",{"class":"fc-cap-link-big"},gfc_P("a",{"class":"fc-cap-link-big"},this.e.MSG_OPTIONS),a.Dg())};
gfc_7[gfc_].Bs=function(){var a=[];a[a[gfc_j]]=gfc_P("div",{"class":"goog-menuitem menuaction-settings"},this.e.MSG_SITE_SETTINGS);a[a[gfc_j]]=this.isSocialShareEnabled?gfc_P("div",{"class":"goog-menuitem menuaction-share"},this.e.MSG_MEMBERS_SHARE):gfc_P("div",{"class":"goog-menuitem menuaction-invite"},this.e.MSG_INVITE_FRIENDS);this.d[gfc_n].isViewerAdmin&&!this.Fb()&&(a[a[gfc_j]]=gfc_P("div",{"class":"goog-menuitem menuaction-manage"},this.e.MSG_MANAGE));a[a[gfc_j]]=gfc_P("div",{"class":"goog-menuitem menuaction-signout"},
this.gb.signOutPrompt||this.e.MSG_SIGN_OUT);a[a[gfc_j]]=gfc_P("div",{"class":"goog-menuseparator fc-menuseparator-line"});a[a[gfc_j]]=gfc_P("div",{"class":"goog-menuitem menuaction-aboutfc"},gfc_P("span",{"class":"fc-small-menu-link"},this.e.MSG_ABOUT_FC));return a};
gfc_7[gfc_].Ds=function(a){a[gfc_Bb]();a=a[gfc_Xb].h()[gfc_ab];a[gfc_3b]("menuaction-settings")?this.Ab():a[gfc_3b]("menuaction-invite")?this.invite():a[gfc_3b]("menuaction-share")?this.share():a[gfc_3b]("menuaction-signout")?this.signout():a[gfc_3b]("menuaction-manage")?this.nq():a[gfc_3b]("menuaction-aboutfc")&&(a=gfc_d[gfc_6a](gfc_0m()+"/friendconnect"),a[gfc_dc]())};gfc_7[gfc_].nq=function(){var a={},b=gfc_a[gfc_k][gfc_sb]().canvas;gfc_Um("lightbox");gfc_a[gfc_k].requestNavigateTo(b,a);return!1};
var gfc_Tn=function(a){for(var b={},c=0;c<a[gfc_j];++c)b[a[c]]=a[c];return b}("HEIGHT BORDER_COLOR CONTENT_BG_COLOR CONTENT_HEADLINE_COLOR CONTENT_LINK_COLOR CONTENT_SECONDARY_TEXT_COLOR CONTENT_SECONDARY_LINK_COLOR CONTENT_TEXT_COLOR ENDCAP_BG_COLOR ENDCAP_LINK_COLOR ENDCAP_TEXT_COLOR FACE_SIZE NUMBER_ROWS".split(" "));
gfc_7[gfc_].s=function(){var a=gfc_Tn,b=[],c=0;this.f(a.HEIGHT);this.Gh()&&(b[c++]=this.j(".fc-thumbnail img {height:%spx;width:%spx}",this.f(a.FACE_SIZE)));b[c++]=this.j(".fc-scroll-botnav, .fc-scroll, .fc-noscroll-botnav {height: %spx;}\n",this.vm);b[c++]=this.j(".fc-members,.fc-members-canvas {border-color: %s;}\n.fc-userpage-itemlist,.fc-userpage-itemlist-canvas,.fc-botcap-short { border-top-color: %s; }\n.fc-topcap,.fc-topverb,.fc-friendreq,.fc-friendreqs,.fc-timeframe { border-bottom-color: %s; }\n",
this.f(a.BORDER_COLOR));this.jf()&&(this.Rk("profile")?b[c++]=".fc-topcap {height: "+this.slimTopCapHeight+"px;}\n":this.Jh()?b[c++]=".fc-topcap {height: 0px;}\n":b[c++]=".fc-topcap {height: "+this.tinyTopCapHeight+"px;}\n");this.Fb()?b[c++]=".fc-userpic-caption {margin-left: 59px;}\n":b[c++]=".fc-userpic-caption {margin-left: 40px;}\n";this.Jh()?b[c++]=".fc-topcap-color {background-color: white;}\n":b[c++]=this.j(".fc-topcap-color {background-color: %s;}\n",this.f(a.ENDCAP_BG_COLOR));this.el()?b[c++]=
".fc-botcap-short {background-color: white;}\n":b[c++]=this.j(".fc-botcap-short {background-color: %s;}\n",this.f(a.ENDCAP_BG_COLOR));b[c++]=this.j(".fc-botverb, .fc-topverb, .fc-members-header {background-color: %s;}\n",this.f(a.ENDCAP_BG_COLOR));b[c++]=this.j(".fc-botverb, .fc-topverb, .fc-members-header {background-color: %s;}\n",this.f(a.ENDCAP_BG_COLOR));b[c++]=this.j(".fc-topcap, .fc-botverb, .fc-topverb, .fc-botcap-short, .fc-header-sectitle, .fc-members-header {color: %s;}\n",this.f(a.ENDCAP_TEXT_COLOR));
b[c++]=this.j(".fc-botverb,.fc-topcap .fc-menutriangle-down, .fc-topcap .fc-menutriangle-up,.fc-topcap a, .fc-topcap a:active, .fc-topcap a:visited,.fc-topcap-link a, .fc-topcap-link a:active, .fc-topcap-link a:visited,.fc-cap-link-big a, .fc-cap-link-big a:active,.fc-left-verb a, .fc-left-verb a:active, .fc-left-verb a:visited,.fc-right-verb a, .fc-right-verb a:active, .fc-right-verb a:visited,.fc-subtle-botcap a, .fc-subtle-botcap a:active, .fc-subtle-botcap a:visited.fc-left-verb-canvas a, .fc-left-verb-canvas a:active, .fc-left-verb-canvas a:visited,.fc-right-verb-canvas a, .fc-right-verb-canvas a:active, .fc-right-verb-canvas a:visited {color: %s;}\n",
this.f(a.ENDCAP_LINK_COLOR));b[c++]=this.j(".fc-content-bg, .fc-subtle-botcap {background-color:%s;}\n",this.f(a.CONTENT_BG_COLOR));b[c++]=this.j(".fc-content a, .fc-content a:active, .fc-content a:visited,\n.fc-item-body a, .fc-item-body a:active, .fc-item-body a:visited,\n.fc-see-all a, .fc-see-all a:active, .fc-see-all a:visited,\n.fc-content-link a, .fc-content-link a:active, .fc-content-link a:visited,\n.fc-content-canvas a, .fc-content-canvas a:active, .fc-content-canvas a:visited {color: %s;}\n",
this.f(a.CONTENT_LINK_COLOR));b[c++]=this.j(".fc-members,.fc-members-canvas {color:%s;}\n",this.f(a.CONTENT_TEXT_COLOR));b[c++]=this.j(".fc-helpful,.fc-on-other-site,.fc-no-elements, .ot-activity-metadata {color:%s;}\n",this.f(a.CONTENT_SECONDARY_TEXT_COLOR));b[c++]=this.j(".fc-faded-link a, .fc-faded-link a:active, .fc-faded-link a:visited, .fc-faded-link-small a, .fc-faded-link-small a:active, .fc-faded-link-small a:visited {color: %s;}\n",this.f(a.CONTENT_SECONDARY_LINK_COLOR));b[c++]=this.j(".fc-sectitle {color: %s;}\n",
this.f(a.CONTENT_HEADLINE_COLOR));return gfc_7.i.s[gfc_y](this)+b[gfc_I]("\n")};gfc_K("goog.peoplesense.gadget.Members",gfc_7);gfc_K("goog.peoplesense.gadget.Members.start",gfc_7[gfc_A]);var gfc_Un=function(a,b,c){gfc_e.Collection[gfc_y](this,a[gfc_kb](c,c+b),c,a[gfc_j]);this.zw=a;this.da=b};gfc_Un.inherits(gfc_e.Collection);gfc_Un[gfc_].all=function(){return this.zw};gfc_Un[gfc_].nb=function(){return this.da};gfc_K("goog.peoplesense.gadget.Members.PagedCollection.prototype.all",gfc_Un[gfc_].all);
gfc_K("goog.peoplesense.gadget.Members.PagedCollection.prototype.getPageSize",gfc_Un[gfc_].nb);
